{{- if (and .Values.ingress.enabled (eq .Values.ingress.solution "GCP")) -}}
{{- $fullName := include "spegg.fullname" . -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $fullName }}
spec:
  redirectToHttps:
    enabled: true
{{- end }}